import assert from 'node:assert/strict';
import path from 'node:path';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {createUnderstandingDraft} from '../src/understanding.js';
import {EditPlanSchema} from '../src/schema.js';
import {proofRun} from '../src/proof.js';
import {readJson, run, writeJson} from '../src/util.js';

const project = path.resolve('test-output/proof-command-fixture'), runDir = path.join(project, 'run');
await mkdir(path.join(project, 'src'), {recursive: true}); await mkdir(runDir, {recursive: true});
await writeFile(path.join(project, 'src/App.ts'), 'export const phases = [{start: 0, frequency: 440}, {start: 1, frequency: 880}];\nexport const result = "The second proof scene uses the second second of the existing audio track.";\n');
const config = {project, url: 'http://127.0.0.1:4173', allowedOrigins: ['http://127.0.0.1:4173'], readyLocator: {testid: 'test-pattern'}, actions: [{type: 'screenshot', name: 'test-pattern'}]};
const draft = await createUnderstandingDraft({project, config, sourceRequests: [{path: 'src/App.ts', startLine: 1, endLine: 2}]});
const analysis = {...draft.manifest, status: 'ready', authoredBy: 'Offline integration fixture', product: {name: 'Proof command fixture', purpose: 'Verify that bounded proofs retain the original source pixels and audio timeline offset.', audience: 'Toolkit regression test authors', primaryOutcome: 'The second scene contains the 880 Hz section of the existing generated audio.'}, safeStart: {...draft.manifest.safeStart, explanation: 'This is an offline rendering fixture; the URL is only a configuration binding and no server or browser capture is started.', evidenceIds: ['source-001']}, flow: [{id: 'second-scene', summary: 'Select the second scene and preserve its original one-second offset.', actionIndexes: [0], evidenceIds: ['source-001'], success: {description: 'The second scene proof contains the second tone section and sixty output frames.', locator: {testid: 'test-pattern'}}}]};
await writeJson(path.join(project, 'demo.understanding.json'), analysis);
await writeJson(path.join(runDir, 'resolved-config.json'), config);
await run('ffmpeg', ['-y', '-v', 'error', '-f', 'lavfi', '-i', 'testsrc2=s=128x72:r=30', '-t', '2', '-c:v', 'libx264', path.join(runDir, 'source.mp4')]);
await run('ffmpeg', ['-y', '-v', 'error', '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000:duration=1', '-f', 'lavfi', '-i', 'sine=frequency=880:sample_rate=48000:duration=1', '-filter_complex', '[0:a][1:a]concat=n=2:v=0:a=1[a]', '-map', '[a]', '-c:a', 'pcm_s16le', path.join(runDir, 'voice.wav')]);
const plan = EditPlanSchema.parse({schemaVersion: 1, runId: 'proof-command-fixture', toolVersion: 'test', profile: {name: 'test', width: 640, height: 360, fps: 60}, durationFrames: 120, transitionFrames: 0, presentation: 'cinematic', title: 'Proof timing', accent: '#7666ec', viewportCss: {width: 128, height: 72}, sourcePixels: {width: 128, height: 72}, fullTrack: 'voice.wav', fullTrackDurationMs: 2000, scenes: ['first', 'second'].map((sceneId, index) => ({sceneId, kind: 'video', sourcePath: 'source.mp4', sourcePixels: {width: 128, height: 72}, sourceStartMs: index * 1000, sourceEndMs: (index + 1) * 1000, sourceDurationMs: 2000, outputStartFrame: index * 60, outputDurationFrames: 60, playbackRate: 1, voiceDurationMs: 0, layout: 'product', title: sceneId, caption: '', camera: [{frame: 0, scale: 1, x: .5, y: .5}], events: []})), provenance: ['Offline generated test pattern and tones, not a browser capture']});
await writeJson(path.join(runDir, 'edit-plan.json'), plan);
const proof = await proofRun(runDir, undefined, ['second']);
assert.equal(proof.technicalStatus, 'passed'); assert.equal(proof.artifacts.length, 4);
assert.deepEqual(proof.selectedScenes[0].frameRange, [60, 119]);
const video = path.join(runDir, proof.artifacts.find((item: any) => item.type === 'video').path), pcm = path.join(runDir, 'proof-audio.pcm');
await run('ffmpeg', ['-y', '-v', 'error', '-i', video, '-ss', '0.2', '-t', '0.6', '-vn', '-ar', '48000', '-ac', '1', '-f', 's16le', pcm]);
const samples = await readFile(pcm); let positiveCrossings = 0;
for (let offset = 2; offset < samples.length; offset += 2) if (samples.readInt16LE(offset - 2) < 0 && samples.readInt16LE(offset) >= 0) positiveCrossings++;
const measuredHz = positiveCrossings / (samples.length / 2 / 48000);
assert.ok(measuredHz > 870 && measuredHz < 890, `Second-scene proof must contain 880 Hz audio, observed ${measuredHz}`);
const cached = await proofRun(runDir, undefined, ['second']); assert.equal(cached.cacheHit, true);
const ledger = await readJson(path.join(runDir, 'logs/attempt-ledger.json')); assert.ok(ledger.attempts.every((item: any) => item.stage === 'render' && item.status === 'passed'));
await writeJson(path.join(project, 'acceptance.json'), {status: 'passed', measuredHz, proof: proof.reportPath, frameRange: [60, 119], cacheHit: true, ledger: 'same parent render stage', subjectiveMotion: 'not-tested', subjectiveListening: 'not-tested'});
process.stdout.write('proof integration passed: same composition, 60 frames, exact second-scene audio offset, parent render ledger and cache\n');
