import React from 'react';
import {AbsoluteFill,Sequence,Img,OffthreadVideo,staticFile,interpolate,Easing,useCurrentFrame,useVideoConfig} from 'remotion';
import type {EditPlan} from '../schema.js';
import {CinematicScene} from './Cinematic.js';
function transform(w:number,h:number,scale:number,x:number,y:number){return {scale,tx:Math.max(w*(1-scale),Math.min(0,w/2-x*w*scale)),ty:Math.max(h*(1-scale),Math.min(0,h/2-y*h*scale))};}
const asset=(p:string)=>staticFile(p.replaceAll('\\','/'));
function Scene({scene,plan}:{scene:EditPlan['scenes'][0];plan:EditPlan}){const f=useCurrentFrame(),{width,height,fps}=useVideoConfig();const vertical=height>width;const pad=width*.048;const availW=width-pad*2;const sourceRatio=plan.sourcePixels.width/plan.sourcePixels.height;const contentH=Math.min(availW/sourceRatio,height*(vertical?.46:.68));const contentW=contentH*sourceRatio;const left=(width-contentW)/2;const top=vertical?height*.28:height*.16;
 const k=scene.camera;const ranges=k.map(v=>v.frame);const scale=k.length>1?interpolate(f,ranges,k.map(v=>v.scale),{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)}):k[0].scale;const x=k.length>1?interpolate(f,ranges,k.map(v=>v.x),{extrapolateRight:'clamp'}):k[0].x;const y=k.length>1?interpolate(f,ranges,k.map(v=>v.y),{extrapolateRight:'clamp'}):k[0].y;const tr=transform(contentW,contentH,scale,x,y);const opacity=interpolate(f,[0,Math.max(1,plan.transitionFrames)],[0,1],{extrapolateRight:'clamp'});
 const last=scene.events.filter(e=>e.frame<=f).at(-1);const next=scene.events.find(e=>e.frame>f);let cx=last?.x??next?.x??.5,cy=last?.y??next?.y??.5;if(last&&next){const t=interpolate(f,[Math.max(last.frame,next.frame-fps*.7),next.frame],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)});cx=last.x+(next.x-last.x)*t;cy=last.y+(next.y-last.y)*t;}
 return <AbsoluteFill style={{opacity,background:'#eef0f7',fontFamily:'Arial, sans-serif',color:'#192035'}}><div style={{position:'absolute',left:pad,top:height*.05,display:'flex',alignItems:'center',gap:16,fontSize:width*.017,fontWeight:700}}><span style={{background:plan.accent,width:16,height:16,borderRadius:5}}/>{plan.title}</div><div style={{position:'absolute',right:pad,top:height*.052,fontSize:width*.011,color:'#65718a'}}>ОБЗОР ПРОДУКТА</div>
 <div style={{position:'absolute',top:top-(vertical?height*.12:height*.055),left:pad,fontSize:width*(vertical?.05:.028),fontWeight:700,maxWidth:width-pad*2}}>{scene.title}</div>
 <div style={{position:'absolute',left,top,width:contentW,height:contentH+width*.021,background:'white',borderRadius:width*.012,overflow:'hidden',boxShadow:'0 22px 65px #17244521',border:'1px solid #d5dbea'}}><div style={{height:width*.021,background:'#fafbff',display:'flex',alignItems:'center',gap:5,paddingLeft:14}}>{['#e5a29f','#e9cb84','#9dc5ad'].map(c=><span key={c} style={{background:c,width:7,height:7,borderRadius:9}}/>)}</div><div style={{width:contentW,height:contentH,overflow:'hidden',position:'relative'}}><div style={{width:contentW,height:contentH,transform:`translate(${tr.tx}px,${tr.ty}px) scale(${tr.scale})`,transformOrigin:'0 0'}}>{scene.kind==='screenshot'?<Img src={asset(scene.sourcePath)} style={{width:'100%',height:'100%'}}/>:<>{f<Math.floor((scene.sourceEndMs-scene.sourceStartMs)/1000*fps/scene.playbackRate)?<OffthreadVideo muted src={asset(scene.sourcePath)} startFrom={Math.round(scene.sourceStartMs/1000*fps)} endAt={Math.round(scene.sourceEndMs/1000*fps)} playbackRate={scene.playbackRate} style={{width:'100%',height:'100%'}}/>:<Img src={asset(scene.holdPath!)} style={{width:'100%',height:'100%'}}/>}</>}{scene.events.length>0&&<div style={{position:'absolute',left:cx*contentW,top:cy*contentH}}><svg width={width*.014} height={width*.018} viewBox="0 0 24 32"><path d="M2 2 L2 26 L9 20 L14 30 L19 27 L14 18 L23 18 Z" fill="#20293f" stroke="white" strokeWidth="2"/></svg></div>}{scene.events.map((e,i)=>{const age=(f-e.frame)/fps;return age>=0&&age<.45?<div key={i} style={{position:'absolute',left:e.x*contentW,top:e.y*contentH,width:(18+age*65),height:(18+age*65),transform:'translate(-50%,-50%)',border:`2px solid ${plan.accent}`,borderRadius:'50%',opacity:1-age/.45}}/>:null;})}</div></div></div>
 <div style={{position:'absolute',left:width*.09,right:width*.09,bottom:height*(vertical?.1:.022),minHeight:height*.075,display:'flex',alignItems:'center',justifyContent:'center',textAlign:'center',fontSize:width*(vertical?.032:.018),lineHeight:1.45,color:'#38445b'}}>{scene.caption}</div><svg width={width} height={4} style={{position:'absolute',bottom:0,left:0}}><rect x={0} y={0} width={width*(scene.outputStartFrame+f)/plan.durationFrames} height={4} fill={plan.accent}/></svg>
 </AbsoluteFill>;}
export function Demo({plan}:{plan:EditPlan}){return <AbsoluteFill style={{background:plan.presentation==='cinematic'?'#11141d':'#eef0f7'}}>{plan.scenes.map((s,i)=><Sequence key={s.sceneId} from={s.outputStartFrame} durationInFrames={s.outputDurationFrames}>{plan.presentation==='cinematic'?<CinematicScene scene={s} plan={plan} index={i}/>:<Scene scene={s} plan={plan}/>}</Sequence>)}</AbsoluteFill>;}
