import os from 'node:os';
import path from 'node:path';
import {mkdir,access,statfs} from 'node:fs/promises';
import {chromium} from 'playwright';
import {run,writeJson,PACKAGE_ROOT} from './util.js';
import {narrationStatus} from './narration.js';
export async function doctor(output=path.resolve('output/doctor')){await mkdir(output,{recursive:true});const checks:any[]=[];const add=(name:string,status:string,evidence:any)=>checks.push({name,status,evidence});add('environment','passed',{platform:process.platform,release:os.release(),node:process.version,cpu:os.cpus()[0]?.model,logicalCpus:os.availableParallelism(),ramBytes:os.totalmem(),freeRamBytes:os.freemem(),ssh:!!process.env.SSH_CONNECTION,wsl:!!process.env.WSL_DISTRO_NAME});for(const exe of ['ffmpeg','ffprobe'])try{add(exe,'passed',(await run(exe,['-version'])).stdout.split('\n')[0]);}catch{add(exe,'blocked','Install FFmpeg from https://ffmpeg.org/download.html in user area and add bin to PATH');}
 for(const encoder of ['libx264','h264_qsv']){const file=path.join(output,`encoder-${encoder}.mp4`);try{await run('ffmpeg',['-y','-v','error','-f','lavfi','-i','testsrc2=s=1280x720:r=144','-t','0.5','-c:v',encoder,'-pix_fmt','yuv420p',file],{timeoutMs:30000});await run('ffmpeg',['-v','error','-i',file,'-f','null','-']);add(encoder,'passed','Real encode + full decode 1280x720@144, 0.5s');}catch(e){add(encoder,'failed',String(e));}}
 try{const b=await chromium.launch({headless:true});add('browser','passed',{type:'playwright-chromium',version:b.version()});await b.close();}catch{try{const b=await chromium.launch({channel:'msedge',headless:true});add('browser','passed',{type:'msedge',version:b.version()});await b.close();}catch(e){add('browser','blocked',String(e));}}
 if(process.platform==='win32')try{const r=await run('pwsh.exe',['-NoProfile','-Command',"Get-CimInstance Win32_VideoController | Select-Object Name,CurrentRefreshRate,CurrentHorizontalResolution,CurrentVerticalResolution | ConvertTo-Json; [Environment]::UserInteractive"]);add('desktop-metadata','passed',r.stdout.trim());}catch(e){add('desktop-metadata','not-tested',String(e));}
 const fs=await statfs(output);add('disk',fs.bavail*fs.bsize>2e9?'passed':'blocked',{freeBytes:fs.bavail*fs.bsize});add('tts',(await narrationStatus()).status,await narrationStatus());const report={schemaVersion:1,checkedAt:new Date().toISOString(),status:checks.some(c=>c.status==='blocked')?'blocked':checks.some(c=>c.status==='failed'&&c.name==='libx264')?'failed':checks.some(c=>c.status==='failed')?'degraded':'passed',checks,limits:['Encoder success is not native capture proof.','Windows only tested; macOS/Linux not-tested.']};await writeJson(path.join(output,'doctor.json'),report);return report;}
export async function setup(output?:string){try{await access(chromium.executablePath());}catch{try{const b=await chromium.launch({channel:'msedge',headless:true});await b.close();}catch{await run(process.execPath,[path.join(PACKAGE_ROOT,'node_modules/playwright/cli.js'),'install','chromium'],{timeoutMs:180000});}}return doctor(output);}
