import path from 'node:path';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {CaptureManifestSchema,DemoConfigSchema,EditPlanSchema,NarrationManifestSchema,StoryboardSchema,profiles,RenderProfileSchema,type EditPlan} from './schema.js';
import {readJson,writeJson,VERSION} from './util.js';
import {msToFrame,mapEvent} from './time.js';
export async function planRun(runDir:string,profileName?:string){
 const cfg=DemoConfigSchema.parse(await readJson(path.join(runDir,'resolved-config.json')));const story=StoryboardSchema.parse(await readJson(path.join(runDir,'storyboard.json')));const cap=CaptureManifestSchema.parse(await readJson(path.join(runDir,'capture/capture-manifest.json')));const voice=NarrationManifestSchema.parse(await readJson(path.join(runDir,'narration/narration-manifest.json')));
 const profile=RenderProfileSchema.parse((profileName??cfg.profile)==='custom'?cfg.customProfile:profiles[profileName??cfg.profile]);const fps=profile.fps,transition=msToFrame(180,fps);let end=0;
 const events=(await readFile(path.join(runDir,'capture/events.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(x=>JSON.parse(x));
 const minDurations=story.scenes.map(s=>Math.max(s.durationSec!==undefined?s.durationSec*1000:3500,(voice.segments.find(n=>n.sceneId===s.sceneId)?.durationMs??0)+700,s.sourceKind==='video'&&s.sourceStartMs!==undefined&&s.sourceEndMs!==undefined?(s.sourceEndMs-s.sourceStartMs)/(s.playbackRate??1)+300:0));
 const minTotal=minDurations.reduce((a,b)=>a+b,0)-(story.scenes.length-1)*180;
 const target=Math.max(cfg.durationSec*1000,minTotal,voice.fullTrack?.durationMs??0);const extra=(target-minTotal)/story.scenes.length;
 const scenes=story.scenes.map((s,i)=>{
  const shot=cap.screenshots.find(v=>v.id===(s.screenshotId??s.sceneId))??cap.screenshots[i];const clip=s.sourceKind==='screenshot'?undefined:s.clipId?cap.clips.find(v=>v.id===s.clipId):(s.sourceKind==='video'||(s.sourceKind===undefined&&i===1)?cap.clips[0]:undefined);if((s.sourceKind==='video'||s.clipId)&&!clip)throw new Error('Requested video source not found for '+s.sceneId);if(!clip&&!shot)throw new Error('No captured source for '+s.sceneId);
  const start=s.sourceStartMs??Number(clip?.sourceStartMs??0),finish=s.sourceEndMs??Number(clip?.sourceEndMs??clip?.durationMs??Math.max(1,Number(shot?.sourceTimeMs??1)));
  const seg=voice.segments.find(n=>n.sceneId===s.sceneId);const outputStartFrame=Math.max(0,end-(i?transition:0));const frames=msToFrame(Math.max(minDurations[i]+extra,clip?(finish-start)/(s.playbackRate??1)+300:0),fps);end=outputStartFrame+frames;
  const scene={sceneId:s.sceneId,kind:(clip?'video':'screenshot') as 'video'|'screenshot',sourcePath:clip?.path??shot!.path,holdPath:clip?(shot?.path??cap.screenshots.at(-1)?.path):undefined,clipId:clip?.id,sourceStartMs:start,sourceEndMs:finish,sourceDurationMs:clip?.durationMs??finish,outputStartFrame,outputDurationFrames:frames,playbackRate:s.playbackRate??1,eyebrow:s.eyebrow,layout:s.layout??(i===0?'hero':i===story.scenes.length-1?'outro':'product'),voicePath:seg?.path,voiceDurationMs:seg?.durationMs??0,title:s.displayText,caption:s.spokenText,camera:s.camera?s.camera.map(k=>({frame:Math.round(k.at*(frames-1)),scale:k.scale,x:k.x,y:k.y})):[{frame:0,scale:1,x:.5,y:.5},{frame:frames-1,scale:i===1?1.025:1.012,x:.5,y:.5}],events:[] as any[]};
  if(clip)scene.events=events.filter(e=>e.clipId===clip.id&&e.type==='click').flatMap(e=>{const t=e.actualActionMs??e.actionTimeMs??e.sourceTimeMs??e.pointerDownMs;const f=mapEvent(t,scene,fps);const pt=e.point??e.coordinates??(Number.isFinite(e.x)?{x:e.x,y:e.y}:null)??(e.boundingBox?{x:e.boundingBox.x+e.boundingBox.width/2,y:e.boundingBox.y+e.boundingBox.height/2}:null);return f===null||!pt?[]:[{frame:f-outputStartFrame,x:pt.x/cfg.viewportCss.width,y:pt.y/cfg.viewportCss.height,type:'click',provenance:'staged-between-measured-endpoints' as const}];});
  return scene;
 });
 const missingFrames=Math.max(0,msToFrame(target,fps)-end);if(missingFrames){scenes[scenes.length-1].outputDurationFrames+=missingFrames;scenes[scenes.length-1].camera.at(-1)!.frame+=missingFrames;end+=missingFrames;}
 const plan=EditPlanSchema.parse({schemaVersion:1,runId:path.basename(runDir),toolVersion:VERSION,profile,durationFrames:end,transitionFrames:transition,presentation:cfg.presentation,brandName:cfg.brand.name,title:story.title,accent:cfg.brand.accent,viewportCss:cfg.viewportCss,sourcePixels:cfg.capturePixels,scenes,fullTrack:voice.fullTrack?.path,fullTrackDurationMs:voice.fullTrack?.durationMs,provenance:['Hybrid presentation: real screenshots with frame-based camera and captions.','Recorded action clips retain measured capture fps; render fps does not add source states.','Cursor paths staged between measured points; segment captions, no word alignment.']});
 await writeJson(path.join(runDir,`edit-plan-${profile.name}.json`),plan);await writeJson(path.join(runDir,'edit-plan.json'),plan);await subtitles(runDir,plan);return plan;
}
async function subtitles(runDir:string,p:EditPlan){await mkdir(path.join(runDir,'subtitles'),{recursive:true});const tc=(ms:number,sep:string)=>new Date(Math.round(ms)).toISOString().slice(11,23).replace('.',sep);const parts=p.scenes.filter(s=>s.voicePath).map((s,i)=>{const start=s.outputStartFrame/p.profile.fps*1000+250;return {i:i+1,start,end:start+s.voiceDurationMs,text:s.caption};});await writeFile(path.join(runDir,'subtitles/ru.srt'),parts.map(s=>`${s.i}\n${tc(s.start,',')} --> ${tc(s.end,',')}\n${s.text}\n`).join('\n'));await writeFile(path.join(runDir,'subtitles/ru.vtt'),'WEBVTT\n\n'+parts.map(s=>`${tc(s.start,'.')} --> ${tc(s.end,'.')}\n${s.text}\n`).join('\n'));}
