import path from 'node:path';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {EditPlanSchema,QualityReportSchema} from './schema.js';
import {probe,run,readJson,writeJson,safeFile,hash} from './util.js';
import {verifyRenderLayers} from './render-proof.js';
import {validateRenderMedia} from './render-input.js';
export async function inspectRun(runDir:string,profile?:string){
 const p=EditPlanSchema.parse(await readJson(path.join(runDir,profile?`edit-plan-${profile}.json`:'edit-plan.json')));await validateRenderMedia(runDir,p);const rendered=await readJson(path.join(runDir,`renders/render-${p.profile.name}.json`));const file=rendered.file;await safeFile(runDir,path.relative(runDir,file));const media=await probe(file);const v=media.streams.find((s:any)=>s.codec_type==='video'),a=media.streams.find((s:any)=>s.codec_type==='audio');const checks:any[]=[];const check=(name:string,ok:boolean,method:string,evidence:any)=>checks.push({name,status:ok?'passed':'failed',method,evidence});
 await run('ffmpeg',['-v','error','-xerror','-i',file,'-f','null','-'],{timeoutMs:300000});check('full-decode',true,'FFmpeg all video/audio packets decode',file);
 const f=JSON.parse((await run('ffprobe',['-v','error','-select_streams','v:0','-show_entries','frame=best_effort_timestamp_time','-of','json',file],{timeoutMs:300000})).stdout).frames.map((x:any)=>Number(x.best_effort_timestamp_time));const gaps=f.slice(1).map((x:number,i:number)=>x-f[i]);check('output-frames',f.length===p.durationFrames,'Decoded frame count and PTS',{count:f.length,expected:p.durationFrames,minGap:Math.min(...gaps),maxGap:Math.max(...gaps)});check('monotonic-timestamps',gaps.every((x:number)=>x>0&&Math.abs(x-1/p.profile.fps)<.0001),'All decoded PTS deltas',{fps:p.profile.fps});check('output-geometry',v.width===p.profile.width&&v.height===p.profile.height,'ffprobe measured pixels',{width:v.width,height:v.height});check('duration',Math.abs(Number(media.format.duration)-p.durationFrames/p.profile.fps)<.15,'Plan vs media duration',{actual:Number(media.format.duration),planned:p.durationFrames/p.profile.fps});check('export-codecs',v.codec_name==='h264'&&a?.codec_name==='aac'&&Number(a.sample_rate)===48000,'ffprobe codec/pixel/audio metadata',{video:v.codec_name,pixelFormat:v.pix_fmt,level:v.level,audio:a?.codec_name,sampleRate:a?.sample_rate});
 const ln=await run('ffmpeg',['-hide_banner','-i',file,'-af','loudnorm=I=-16:TP=-1:LRA=11:print_format=json','-f','null','-'],{timeoutMs:300000});const lm=ln.stderr.match(/\{\s*"input_i"[\s\S]*?\}/);const loudness=lm?JSON.parse(lm[0]):{};check('final-aac-loudness',Math.abs(Number(loudness.input_i)+16)<1&&Number(loudness.input_tp)<=-1,'Decoded AAC integrated loudness / true peak',loudness);
 check('source-ranges-and-voice',true,'Strict EditPlan validation before render',{schema:'EditPlanSchema',scenes:p.scenes.map(s=>({sceneId:s.sceneId,sourceRange:[s.sourceStartMs,s.sourceEndMs],voiceDurationMs:s.voiceDurationMs}))});
 const review=path.join(runDir,'review');await mkdir(review,{recursive:true});const frames=p.scenes.flatMap(s=>[Math.max(0,s.outputStartFrame-1),s.outputStartFrame+Math.max(1,p.transitionFrames),s.outputStartFrame+Math.floor(s.outputDurationFrames/2),s.outputStartFrame+s.outputDurationFrames-1,...s.camera.map(k=>s.outputStartFrame+k.frame),...s.events.flatMap(e=>[-Math.ceil(p.profile.fps*.1),0,Math.ceil(p.profile.fps*.1)].map(d=>Math.max(s.outputStartFrame,Math.min(s.outputStartFrame+s.outputDurationFrames-1,s.outputStartFrame+e.frame+d))))]);frames.push(p.durationFrames-1);for(const frame of [...new Set(frames)])await run('ffmpeg',['-y','-v','error','-ss',String(frame/p.profile.fps),'-i',file,'-frames:v','1',path.join(review,`frame-${p.profile.name}-${frame}.png`)]);await run('ffmpeg',['-y','-v','error','-i',file,'-vf',`fps=${9/(p.durationFrames/p.profile.fps)},scale=640:-1,tile=3x3`,'-frames:v','1',path.join(review,'contact-sheet.png')],{timeoutMs:300000});
 const text=await Promise.all(['resolved-config.json','storyboard.json','capture/capture-manifest.json','capture/events.jsonl','narration/narration-manifest.json','edit-plan.json'].map(f=>readFile(path.join(runDir,f),'utf8')));const secrets=/(?:sk-[A-Za-z0-9]{20,}|Bearer\s+[A-Za-z0-9._-]{20,}|(?:password|api[_-]?key|access_token)\s*[=:]\s*["']?[^\s"']{8,})/i;check('known-secret-patterns',!text.some(t=>secrets.test(t)),'Regex on exported metadata; not a PII guarantee',{demoData:true});
 const black=await run('ffmpeg',['-hide_banner','-i',file,'-vf','blackdetect=d=0.15:pix_th=0.05','-an','-f','null','-'],{timeoutMs:300000});check('unintentional-black-scenes',!black.stderr.includes('black_start:'),'Decoded blackdetect; preset has no intended full black scenes',black.stderr.match(/black_start:[^\n]+/g)??[]);
 const layerProof=await verifyRenderLayers(file,p);await writeJson(path.join(review,`render-layer-proof-${p.profile.name}.json`),layerProof);checks.push({name:'rendered-animation-frames',status:layerProof.status,method:'Decoded progress edge geometry versus absolute composition frame; only sampled layer proof',evidence:`render-layer-proof-${p.profile.name}.json`});
 checks.push({name:'native-capture-144',status:'degraded',method:'Capture provenance and separate benchmark; output fps excluded',evidence:'Hybrid presentation uses screenshots and source clips; native144 not asserted'},{name:'visual-review',status:'not-tested',method:'Agent must inspect contact sheet + selected full-resolution frames',evidence:'review/contact-sheet.png'},{name:'motion-review',status:'not-tested',method:'Watch at normal speed; still frames do not prove motion',evidence:null},{name:'subjective-listening',status:'not-tested',method:'Listen to real Russian narration',evidence:null});
 const report=QualityReportSchema.parse({schemaVersion:1,runId:path.basename(runDir),status:checks.some(c=>c.status==='failed')?'failed':'degraded',checks,limitations:['Native 144 capture is a separate gate; this artifact is hybrid.','No word alignment: captions follow complete speech segments.','Agent visual/listening status is recorded separately, never inferred from ffprobe.','Static source scenes intentionally freeze product state; animated camera is generated by Remotion.']});await writeJson(path.join(review,'quality-report.json'),report);await writeJson(path.join(review,`quality-report-${p.profile.name}.json`),report);await writeFile(path.join(review,'quality-report.md'),`# Quality report: ${report.status}\n\n`+checks.map(c=>`- ${c.status}: ${c.name} — ${c.method}`).join('\n')+'\n');await writeJson(path.join(review,'provenance.json'),{schemaVersion:1,runId:p.runId,source:await readJson(path.join(runDir,'capture/capture-manifest.json')),output:{file,sha256:hash(await readFile(file)),width:v.width,height:v.height,frames:f.length,fps:p.profile.fps},syntheticVoice:await readJson(path.join(runDir,'narration/narration-manifest.json')),claims:p.provenance});return report;
}
