import {z} from 'zod';
export const Status=z.enum(['passed','failed','blocked','not-tested','degraded']);
const px=z.object({width:z.number().int().positive().max(7680),height:z.number().int().positive().max(7680)}).strict();
export const LocatorSchema=z.union([z.object({role:z.string(),name:z.string().optional()}).strict(),z.object({label:z.string()}).strict(),z.object({text:z.string()}).strict(),z.object({testid:z.string()}).strict(),z.object({css:z.string()}).strict()]);
export const ActionSchema=z.object({type:z.enum(['click','fill','type','hover','scroll','waitFor','pause','marker','screenshot']),locator:LocatorSchema.optional(),value:z.string().optional(),ms:z.number().min(0).max(30000).optional(),x:z.number().optional(),y:z.number().optional(),name:z.string().optional()}).strict();
const CameraCueSchema=z.object({at:z.number().min(0).max(1),scale:z.number().min(1).max(3),x:z.number().min(0).max(1),y:z.number().min(0).max(1)}).strict();
export const StorySceneSchema=z.object({sceneId:z.string(),meaning:z.string().default(''),visibleResult:z.string().default(''),displayText:z.string(),spokenText:z.string(),eventIds:z.array(z.string()).default([]),pronunciations:z.record(z.string(),z.string()).optional(),screenshotId:z.string().optional(),sourceScreenshot:z.string().optional(),clipId:z.string().optional(),sourceKind:z.enum(['screenshot','video']).optional(),layout:z.enum(['hero','product','detail','outro']).optional(),eyebrow:z.string().max(64).optional(),durationSec:z.number().min(.5).max(120).optional(),playbackRate:z.number().min(.5).max(2).optional(),camera:z.array(CameraCueSchema).min(1).optional(),sourceStartMs:z.number().nonnegative().optional(),sourceEndMs:z.number().positive().optional()}).strict().superRefine((s,ctx)=>{if(s.camera?.some((k,i,a)=>i>0&&k.at<=a[i-1].at))ctx.addIssue({code:'custom',message:'Camera cues must have strictly increasing normalized times'});});
export const StoryboardSchema=z.object({schemaVersion:z.literal(1),title:z.string(),scenes:z.array(StorySceneSchema).min(1)}).strict();
export const DemoConfigSchema=z.object({schemaVersion:z.literal(1).default(1),project:z.string().optional(),analysisFile:z.string().optional(),url:z.string().url(),allowedOrigins:z.array(z.string().refine(v=>{try{return new URL(v).origin===v}catch{return false}},'Allowlist entries must be bare HTTP(S) origins')).default([]),start:z.object({command:z.string(),args:z.array(z.string()),cwd:z.string().optional(),timeoutMs:z.number().positive().max(120000).optional()}).strict().optional(),readyLocator:LocatorSchema.optional(),auth:z.object({required:z.boolean().optional(),expectedLocator:LocatorSchema.optional(),timeoutMs:z.number().positive().max(600000).optional()}).strict().optional(),viewportCss:px.default({width:1600,height:900}),capturePixels:px.default({width:2560,height:1440}),captureTargetFps:z.number().positive().max(240).default(144),durationSec:z.number().min(3).max(300).default(30),language:z.literal('ru-RU').default('ru-RU'),voice:z.enum(['female','male']).default('female'),voiceId:z.string().optional(),ttsProvider:z.enum(['auto','windows-sapi','edge-neural']).default('auto'),allowExternalTts:z.boolean().default(false),speechRatePercent:z.number().int().min(-10).max(10).default(0),presentation:z.enum(['classic','cinematic']).default('cinematic'),profile:z.string().default('web-60'),customProfile:z.object({name:z.literal('custom'),width:z.number().int().positive().max(7680),height:z.number().int().positive().max(7680),fps:z.number().int().positive().max(240)}).strict().optional(),strictNativeFps:z.boolean().default(false),actions:z.array(ActionSchema),storyboard:StoryboardSchema,brand:z.object({name:z.string(),accent:z.string().regex(/^#[0-9a-fA-F]{6}$/)}).default({name:'Product Demo',accent:'#7666ec'}),musicFile:z.string().optional()}).strict().superRefine((c,ctx)=>{const u=new URL(c.url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||/token|password|api.?key|secret|authorization/i.test(decodeURIComponent(u.hash))||[...u.searchParams.keys()].some(k=>/token|password|api.?key|secret|authorization/i.test(k)))ctx.addIssue({code:'custom',message:'URL must be HTTP(S) without credentials or secret query parameters'});for(const a of c.actions)if(['fill','type'].includes(a.type)&&/password|парол|credit|card|секрет|token|api.?key/i.test(JSON.stringify(a.locator)))ctx.addIssue({code:'custom',message:'Sensitive inputs belong in unrecorded auth handoff'});});
export type DemoConfig=z.infer<typeof DemoConfigSchema>;
export function defineDemoConfig(config:z.input<typeof DemoConfigSchema>){return config;}
export const RenderProfileSchema=z.object({name:z.string().regex(/^[a-z0-9][a-z0-9_-]{0,63}$/i),width:z.number().int().positive().max(7680),height:z.number().int().positive().max(7680),fps:z.number().int().min(1).max(240)}).strict().refine(p=>p.width%2===0&&p.height%2===0,'H264 dimensions must be even');
export const profiles:Record<string,z.infer<typeof RenderProfileSchema>>={'master-144':{name:'master-144',width:2560,height:1440,fps:144},'web-60':{name:'web-60',width:1920,height:1080,fps:60},vertical:{name:'vertical',width:1080,height:1920,fps:60},square:{name:'square',width:1080,height:1080,fps:60},'4k-60':{name:'4k-60',width:3840,height:2160,fps:60}};
export const InteractionEventSchema=z.object({eventId:z.string(),type:z.string(),clipId:z.string(),pageId:z.string()}).passthrough();
export const CaptureManifestSchema=z.object({schemaVersion:z.literal(1),clips:z.array(z.object({id:z.string(),path:z.string(),durationMs:z.number().positive(),width:z.number().positive(),height:z.number().positive(),fps:z.number().positive()}).passthrough()),screenshots:z.array(z.object({id:z.string(),path:z.string(),width:z.number().positive(),height:z.number().positive()}).passthrough())}).passthrough();
export const NarrationManifestSchema=z.object({schemaVersion:z.literal(1),provider:z.string(),segments:z.array(z.object({sceneId:z.string(),path:z.string(),durationMs:z.number().positive()}).passthrough()),fullTrack:z.object({path:z.string(),durationMs:z.number().positive()}).passthrough().optional()}).passthrough();
export const CameraSchema=z.object({frame:z.number().int().nonnegative(),scale:z.number().min(1).max(3),x:z.number().min(0).max(1),y:z.number().min(0).max(1)}).strict();
export const EditSceneSchema=z.object({sceneId:z.string(),kind:z.enum(['screenshot','video']),sourcePath:z.string(),sourcePixels:px.optional(),holdPath:z.string().optional(),clipId:z.string().optional(),sourceStartMs:z.number().nonnegative(),sourceEndMs:z.number().positive(),sourceDurationMs:z.number().positive(),outputStartFrame:z.number().int().nonnegative(),outputDurationFrames:z.number().int().positive(),playbackRate:z.number().positive().max(4),voicePath:z.string().optional(),voiceDurationMs:z.number().nonnegative(),layout:z.enum(['hero','product','detail','outro']).optional(),eyebrow:z.string().max(64).optional(),title:z.string().max(120),caption:z.string().max(500),camera:z.array(CameraSchema).min(1),events:z.array(z.object({frame:z.number().int().nonnegative(),x:z.number().min(0).max(1),y:z.number().min(0).max(1),type:z.string(),provenance:z.literal('staged-between-measured-endpoints')}).strict())}).strict().superRefine((s,ctx)=>{
 if(s.sourceEndMs>s.sourceDurationMs+1||s.sourceEndMs<=s.sourceStartMs)ctx.addIssue({code:'custom',message:'Source range out of bounds'});
 if(s.camera.some((k,i,a)=>k.frame>=s.outputDurationFrames||(i>0&&k.frame<=a[i-1].frame)))ctx.addIssue({code:'custom',message:'Camera frames must increase strictly and stay inside the scene'});
 if(s.events.some(e=>e.frame>=s.outputDurationFrames))ctx.addIssue({code:'custom',message:'Interaction event frame is outside the scene'});
});
export const EditPlanSchema=z.object({schemaVersion:z.literal(1),runId:z.string(),toolVersion:z.string(),profile:RenderProfileSchema,durationFrames:z.number().int().positive(),transitionFrames:z.number().int().nonnegative(),presentation:z.enum(['classic','cinematic']).optional(),brandName:z.string().optional(),title:z.string(),accent:z.string(),viewportCss:px,sourcePixels:px,scenes:z.array(EditSceneSchema).min(1),fullTrack:z.string().optional(),fullTrackDurationMs:z.number().nonnegative().optional(),provenance:z.array(z.string())}).strict().superRefine((p,ctx)=>{
 if(p.fullTrack&&(!p.fullTrackDurationMs||p.fullTrackDurationMs>p.durationFrames/p.profile.fps*1000+1))ctx.addIssue({code:'custom',message:'Full narration exceeds composition duration'});
 let end=0;p.scenes.forEach((s,i)=>{
  if(s.outputStartFrame!==Math.max(0,end-(i?p.transitionFrames:0)))ctx.addIssue({code:'custom',message:'Scene overlap inconsistent with transition duration'});
  if(p.transitionFrames>=s.outputDurationFrames)ctx.addIssue({code:'custom',message:'Transition must be shorter than its scene'});
  if((s.voiceDurationMs>0?(s.voiceDurationMs+250)/1000*p.profile.fps:0)>s.outputDurationFrames-p.transitionFrames+1)ctx.addIssue({code:'custom',message:'Narration clipped by scene/transition'});
  if(s.kind==='video'&&Math.ceil((s.sourceEndMs-s.sourceStartMs)/s.playbackRate*p.profile.fps/1000-1e-8)>s.outputDurationFrames)ctx.addIssue({code:'custom',message:'Selected video range exceeds scene duration'});
  end=s.outputStartFrame+s.outputDurationFrames;
 });
 if(end!==p.durationFrames)ctx.addIssue({code:'custom',message:'Plan duration mismatch'});
});
export type EditPlan=z.infer<typeof EditPlanSchema>;
export const QualityReportSchema=z.object({schemaVersion:z.literal(1),runId:z.string(),status:Status,artifactSha256:z.string().regex(/^[a-f0-9]{64}$/).optional(),planSha256:z.string().regex(/^[a-f0-9]{64}$/).optional(),deliveryStatus:z.enum(['review-candidate','changes-required','reviewed']).optional(),checks:z.array(z.object({name:z.string(),status:Status,method:z.string(),evidence:z.any()})),limitations:z.array(z.string())}).strict();
